export interface Game {
  id: string;
  name: string;
  version: string;
  size: string;
  downloads: string;
  rating: number;
  description: string;
  modFeatures: string[];
  category: string;
  imageColor: string;
  imageUrl: string;
}

export const GAMES: Game[] = [
  {
    id: "roblox",
    name: "Roblox",
    version: "2.650.742",
    size: "185 MB",
    downloads: "847K+",
    rating: 4.7,
    description: "Explore millions of user-created 3D worlds. Create, share, and be anything you can imagine in the ultimate virtual universe.",
    modFeatures: ["Unlimited Robux", "Mod Menu", "God Mode", "Fly & Speed Hacks"],
    category: "RPG",
    imageColor: "from-slate-800 to-red-950",
    imageUrl: "https://i.imgur.com/fJMMzA9.jpeg",
  },
  {
    id: "zooba",
    name: "ZOOBA",
    version: "4.12.0",
    size: "168 MB",
    downloads: "1M+",
    rating: 4.8,
    description: "Battle Royale like never before! Fight with diverse zoo animals in this epic action-packed survival game.",
    modFeatures: ["Unlimited Gems", "All Characters Unlocked", "No Ads", "Map Hack"],
    category: "Action",
    imageColor: "from-orange-500 to-red-600",
    imageUrl: "https://i.imgur.com/r0KGnF0.png",
  },
  {
    id: "truckers-europe-3",
    name: "Truckers of Europe 3",
    version: "0.40.2",
    size: "450 MB",
    downloads: "500K+",
    rating: 4.7,
    description: "Experience the most realistic truck driving simulation. Travel across Europe delivering cargo in powerful trucks.",
    modFeatures: ["Unlimited Money", "Max Fuel", "All Trucks Unlocked", "Realistic Physics Mod"],
    category: "Simulation",
    imageColor: "from-blue-600 to-indigo-800",
    imageUrl: "https://i.imgur.com/MUbuYOf.jpeg",
  },
  {
    id: "geometry-dash",
    name: "Geometry Dash",
    version: "2.2.13",
    size: "85 MB",
    downloads: "10M+",
    rating: 4.9,
    description: "Jump and fly your way through danger in this rhythm-based action platformer!",
    modFeatures: ["All Levels Unlocked", "God Mode", "Unlimited Orbs", "Custom Icons"],
    category: "Arcade",
    imageColor: "from-emerald-500 to-teal-700",
    imageUrl: "https://i.imgur.com/j2WAmkq.png",
  },
  {
    id: "football-league-2026",
    name: "Football League 2026",
    version: "1.0.5",
    size: "320 MB",
    downloads: "250K+",
    rating: 4.6,
    description: "The ultimate football experience. Manage your team, climb the ranks, and dominate the world stage.",
    modFeatures: ["Unlimited Budget", "Max Player Stats", "All Kits Unlocked", "Stadium Upgrades"],
    category: "Sports",
    imageColor: "from-green-500 to-lime-600",
    imageUrl: "https://i.imgur.com/OvKZ97w.png",
  },
  {
    id: "off-road-4x4-5",
    name: "Off Road 4x4 Driving Sim 5",
    version: "5.2.1",
    size: "210 MB",
    downloads: "150K+",
    rating: 4.5,
    description: "Conquer the toughest terrains with powerful 4x4 vehicles. Physics-based off-road challenges await.",
    modFeatures: ["Unlimited Coins", "All 4x4s Unlocked", "Free Upgrades", "No Ads"],
    category: "Simulation",
    imageColor: "from-amber-600 to-yellow-800",
    imageUrl: "https://i.imgur.com/n9nblBg.png",
  },
  {
    id: "coin-master",
    name: "Coin Master",
    version: "3.5.1520",
    size: "68 MB",
    downloads: "10M+",
    rating: 4.6,
    description: "Spin the wheel, raid villages, and build your ultimate Viking empire in this addictive social casual game!",
    modFeatures: ["Unlimited Spins", "Unlimited Coins", "Auto Spin Mode", "Card Collection Hack"],
    category: "Arcade",
    imageColor: "from-yellow-400 to-amber-600",
    imageUrl: "https://i.imgur.com/GQrCDYk.jpeg",
  },
  {
    id: "mobile-legends",
    name: "Mobile Legends: Bang Bang",
    version: "1.8.78",
    size: "142 MB",
    downloads: "5M+",
    rating: 4.7,
    description: "Join millions of players in real-time 5v5 MOBA battles! Choose your favorite heroes and build the perfect team.",
    modFeatures: ["All Heroes Unlocked", "Unlimited Diamonds", "Map Hack Radar", "No Skill Cooldown"],
    category: "Action",
    imageColor: "from-sky-700 to-blue-950",
    imageUrl: "https://i.imgur.com/NtE8mqN.jpeg",
  },
  {
    id: "fc-mobile",
    name: "FC Mobile (EA Sports FC)",
    version: "21.1.03",
    size: "348 MB",
    downloads: "10M+",
    rating: 4.8,
    description: "Build an Ultimate Team with elite football stars, compete in world-class tournaments, and experience true soccer simulation.",
    modFeatures: ["Mod Menu Toggle", "Unlimited FC Points", "All Players Unlocked", "Perfect Kick Accuracy"],
    category: "Sports",
    imageColor: "from-green-600 to-emerald-950",
    imageUrl: "https://i.imgur.com/O4n4XBi.jpeg",
  },
  {
    id: "stumble-guys",
    name: "Stumble Guys",
    version: "0.72.1",
    size: "124 MB",
    downloads: "8M+",
    rating: 4.7,
    description: "Run, stumble, and fall through hilarious obstacle courses in this massive multiplayer knockout party game.",
    modFeatures: ["Unlimited Gems", "All Skins Unlocked", "Custom Speed Multiplier", "Anti-Disconnect"],
    category: "Arcade",
    imageColor: "from-fuchsia-500 to-purple-800",
    imageUrl: "https://i.imgur.com/KgNDFuG.png",
  },
  {
    id: "shadow-fight-2",
    name: "Shadow Fight 2",
    version: "2.35.0",
    size: "145 MB",
    downloads: "15M+",
    rating: 4.9,
    description: "The perfect offline martial arts classic! Descend into the underworld to close the Gates of Shadows.",
    modFeatures: ["Unlimited Gems & Coins", "Max Level 52 Unlocked", "All Weapons Custom Mode", "No Energy Limit"],
    category: "Action",
    imageColor: "from-slate-800 to-neutral-950",
    imageUrl: "https://i.imgur.com/IQHX8U8.jpeg",
  },
  {
    id: "clash-of-clans",
    name: "Clash of Clans",
    version: "16.253.15",
    size: "298 MB",
    downloads: "50M+",
    rating: 4.8,
    description: "Join the clan, raise an army, and lead your fortress to glory in Supercell's legendary strategic war game.",
    modFeatures: ["Unlimited Gems & Gold", "Max Town Hall Level", "Instant Troops Training", "Unlimited Elixir Reserves"],
    category: "Strategy",
    imageColor: "from-amber-700 to-stone-900",
    imageUrl: "https://i.imgur.com/BDcOaO8.png",
  },
  {
    id: "clash-royale",
    name: "Clash Royale",
    version: "6.256.12",
    size: "212 MB",
    downloads: "12M+",
    rating: 4.7,
    description: "Enter the arena! Duel players in epic card-based strategy battles to destroy enemy towers and win trophies.",
    modFeatures: ["Unlimited Gems & Gold", "Max Card Levels", "Infinite Elixir Mode", "Private Server Enabled"],
    category: "Strategy",
    imageColor: "from-red-600 to-blue-800",
    imageUrl: "https://i.imgur.com/oOncF2y.png",
  },
  {
    id: "hay-day",
    name: "Hay Day",
    version: "1.61.220",
    size: "146 MB",
    downloads: "3M+",
    rating: 4.6,
    description: "Build a prosperous farm, trade fresh goods with neighbors, and enjoy a peaceful rural life in this colorful simulation.",
    modFeatures: ["Unlimited Seeds & Items", "Unlimited Coins", "Unlimited Gems", "Max Level Expansion Pack"],
    category: "Simulation",
    imageColor: "from-yellow-600 to-orange-850",
    imageUrl: "https://i.imgur.com/TOUcIEX.jpeg",
  },
  {
    id: "pokemon-go",
    name: "Pokémon GO",
    version: "0.315.0",
    size: "122 MB",
    downloads: "20M+",
    rating: 4.6,
    description: "Step outside and catch Pokémon in the real world! Spoof your location and catch rare shiny creatures effortlessly.",
    modFeatures: ["GPS Joystick Spoof", "Auto-Walk Multiplier", "100% Catch Rate Trick", "Unlimited Pokéballs Trick"],
    category: "RPG",
    imageColor: "from-cyan-500 to-indigo-900",
    imageUrl: "https://i.imgur.com/jXMlml1.jpeg",
  },
  {
    id: "fortnite",
    name: "Fortnite",
    version: "30.00.0",
    size: "180 MB",
    downloads: "5M+",
    rating: 4.5,
    description: "Epic's premier battle royale on mobile! Build fortresses, survive storm shrinking circles, and claim Victory Royale.",
    modFeatures: ["Aimbot Lock", "Wall Hack ESP", "Unlimited V-Bucks Mode", "All Character Skins Unlocked"],
    category: "Action",
    imageColor: "from-indigo-600 to-pink-800",
    imageUrl: "https://i.imgur.com/5JI6NoD.jpeg",
  }
];
